version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Australia/Sydney"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Australia/Sydney"
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
      timezone: "Australia/Sydney"
