baseURL: https://cloudartisan.com/
languageCode: en-us
title: Cloud Artisan
theme: congo

enableRobotsTXT: true

# Allow raw HTML in content
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

# Suppress warnings
ignoreLogs: ['warning-goldmark-raw-html']

# Congo theme configuration
# Following "Getting Started" guide from https://jpanther.github.io/congo/docs/installation/
module:
  imports:
    - path: github.com/jpanther/congo/v2

# Theme-specific configuration
params:
  description: "Cloud Computing, Retro Computing, Software Development, Martial Arts"
  copyright: "&copy; David Taylor 2010-{year}"
  
  colorScheme: ocean
  defaultAppearance: light
  autoSwitchAppearance: true
  
  # Custom CSS
  customCSS:
    - assets/css/custom.css
  
  homepage:
    layout: profile
    showRecent: false
  
  article:
    showDate: true
    showAuthor: true
    showBreadcrumbs: true
    showDraftLabel: true
    showEdit: false
    showTableOfContents: true
    showReadingTime: true
    sharingLinks: 
      - twitter
      - linkedin
      - reddit
      
  # Hide dates and reading time on specific page types
  pages:
    showDate: false
    showReadingTime: false
    
  # Specific settings for projects section
  list:
    showDate: false
    showReadingTime: false
    
  # Settings for single project pages
  projects:
    showBreadcrumbs: false

  # Configure the profile mode
  profileMode:
    enabled: true
    title: David Taylor
    subtitle: "Cloud Artisan"
    imageUrl: "/images/profile.png"
    imageTitle: David Taylor

  footer:
    showCopyright: true
    showThemeAttribution: true
    showAppearanceSwitcher: true
    showScrollToTop: true

  social:
    - name: Twitter
      url: https://twitter.com/davidltaylor
      icon: brand-twitter
    - name: Mastodon
      url: https://fosstodon.org/@cloudartisan
      rel: me noopener
      icon: brand-mastodon
    - name: GitHub
      url: https://github.com/cloudartisan
      icon: brand-github
    - name: LinkedIn
      url: https://www.linkedin.com/in/davidleslietaylor/
      icon: brand-linkedin

languages:
  en:
    languageName: English
    weight: 1
    params:
      author:
        name: David Taylor
        image: images/profile.png
        headline: Cloud Artisan
        links:
          - twitter: https://twitter.com/davidltaylor
          - mastodon: https://fosstodon.org/@cloudartisan
          - github: https://github.com/cloudartisan
          - linkedin: https://www.linkedin.com/in/davidleslietaylor/

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 10
    - name: Projects
      url: /projects/
      weight: 20
    - name: About
      url: /about/
      weight: 30