name: Deploy Hugo site

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Debug Environment
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Hugo configuration:"
          cat config.yaml
          echo "Hugo module configuration:"
          hugo mod graph || echo "Hugo mod graph failed"
          echo "Go mod configuration:"
          cat go.mod || echo "No go.mod file found"

      - name: Setup Hugo Modules
        run: |
          hugo mod tidy
          hugo mod get -u github.com/jpanther/congo/v2

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # deploying to gh-pages branch
          # Remove the CNAME setting until custom domain is properly configured
          # cname: cloudartisan.com